// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	traffic "github.com/qianjisantech/gosmo/internal/handler/traffic"
	"github.com/qianjisantech/gosmo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/traffic/pool/page",
				Handler: traffic.TrafficPoolQueryPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/gosmo"),
	)
}