// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	agent "agent/internal/handler/agent"
	"agent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/agent/run",
				Handler: agent.AgentRunHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
