// Code generated by goctl. DO NOT EDIT.
package types

type TrafficPoolQueryPageRequest struct {
	Key string `json:"key"`
}

type TrafficPoolQueryPageResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
