// Code generated by goctl. DO NOT EDIT.
package types

type KafkaSyncProducerRequest struct {
}

type KafkaSyncProducerResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
