// Code generated by goctl. DO NOT EDIT.
package types

type AgentRunRequest struct {
	ListenPort string `json:"listenPort"`
}

type AgentRunResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
